export const GETTING_QUOTES = 'GETTING_QUOTES';
export const GET_QUOTES_SUCCESS = 'GET_QUOTES_SUCCESS';
export const GET_QUOTES_FAILURE = 'GET_QUOTES_FAILURE';

export const ADDING_QUOTE = 'ADDING_QUOTE';
export const ADD_QUOTE_SUCCESS = 'ADD_QUOTE_SUCCESS';
export const ADD_QUOTE_FAILURE = 'ADD_QUOTE_FAILURE';

export const DELETING_QUOTE = 'DELETING_QUOTE';
export const DELETE_QUOTE_SUCCESS = 'DELETE_QUOTE_SUCCESS';
export const DELETE_QUOTE_FAILURE = 'DELETE_QUOTE_FAILURE';

export const MARKING_FAVOURITE = 'MARKING_FAVOURITE';
export const MARK_FAVOURITE_SUCCESS = 'MARK_FAVOURITE_SUCCESS';
export const MARK_FAVOURITE_FAILURE = 'MARK_FAVOURITE_FAILURE';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const MAKE_QUOTE_OF_THE_DAY = 'MAKE_QUOTE_OF_THE_DAY';